version: '3.8'

services:
  bus-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
      - PORT=8008
      - MONGODB_URI=mongodb+srv://nakshatramanglik14:naksh1414@cluster0.3lrl1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongodb
    networks:
      - bus-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bus-network

volumes:
  mongodb_data:

networks:
  bus-network:
    driver: bridge